import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { getAuthorizationUrl } from "@/lib/hmrc/client";
import { verifyToken } from "@/lib/auth";

/**
 * GET /api/hmrc/auth
 *
 * Initiates the HMRC OAuth 2.0 flow. Requires a valid Pro license token.
 * Redirects the user to HMRC's authorization page.
 */
export async function GET(request: NextRequest) {
  const token = request.nextUrl.searchParams.get("token");

  if (!token) {
    return NextResponse.json(
      { error: "License token is required." },
      { status: 401 }
    );
  }

  // Verify the user has a valid HMAC-signed license token (from LemonSqueezy activation)
  const payload = verifyToken(token);
  if (!payload) {
    return NextResponse.json(
      { error: "Invalid or expired license token." },
      { status: 401 }
    );
  }

  // Ensure user has a Pro subscription
  if (payload.plan !== "pro") {
    return NextResponse.json(
      { error: "HMRC features require a Pro subscription." },
      { status: 403 }
    );
  }

  // Generate a random state parameter for CSRF protection
  const state = crypto.randomBytes(32).toString("hex");

  // HMAC-sign the state so the callback can verify it was generated by us
  // without needing server-side session storage
  const stateData = { state, token, ts: Date.now() };
  const stateJson = JSON.stringify(stateData);
  const signature = crypto
    .createHmac("sha256", process.env.HMRC_CLIENT_SECRET || "")
    .update(stateJson)
    .digest("hex");
  const statePayload = Buffer.from(
    JSON.stringify({ ...stateData, sig: signature })
  ).toString("base64url");

  const authUrl = getAuthorizationUrl(statePayload);

  return NextResponse.redirect(authUrl);
}
