import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { exchangeCodeForTokens } from "@/lib/hmrc/client";
import { verifyToken } from "@/lib/auth";

/**
 * GET /api/hmrc/callback
 *
 * HMRC redirects here after the user grants (or denies) access.
 * Exchanges the authorization code for access + refresh tokens,
 * then redirects the user back to the dashboard with tokens
 * in an HMAC-signed query parameter that the client reads once and clears.
 */
export async function GET(request: NextRequest) {
  const code = request.nextUrl.searchParams.get("code");
  const stateParam = request.nextUrl.searchParams.get("state");
  const error = request.nextUrl.searchParams.get("error");
  const errorDescription = request.nextUrl.searchParams.get(
    "error_description"
  );

  // Handle HMRC denial
  if (error) {
    const dashboardUrl = new URL("/dashboard/hmrc-connect", request.url);
    dashboardUrl.searchParams.set(
      "error",
      errorDescription || "HMRC authorization was denied."
    );
    return NextResponse.redirect(dashboardUrl);
  }

  if (!code || !stateParam) {
    return NextResponse.json(
      { error: "Missing authorization code or state." },
      { status: 400 }
    );
  }

  // Decode and verify state with HMAC signature
  let stateData: { state: string; token: string; ts: number };
  try {
    const decoded = JSON.parse(
      Buffer.from(stateParam, "base64url").toString()
    );
    const { sig, ...data } = decoded;

    // Verify HMAC signature to confirm state was generated by us (CSRF protection)
    const expected = crypto
      .createHmac("sha256", process.env.HMRC_CLIENT_SECRET || "")
      .update(JSON.stringify(data))
      .digest("hex");

    if (!sig || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) {
      return NextResponse.json(
        { error: "Invalid state signature. Possible CSRF attack." },
        { status: 403 }
      );
    }

    stateData = data;
  } catch {
    return NextResponse.json({ error: "Invalid state parameter." }, { status: 400 });
  }

  // Verify the license token is still valid (HMAC-signed only)
  const payload = verifyToken(stateData.token);
  if (!payload) {
    return NextResponse.json(
      { error: "License token expired during HMRC authorization." },
      { status: 401 }
    );
  }

  // Check state isn't too old (15 minutes max)
  if (Date.now() - stateData.ts > 15 * 60 * 1000) {
    return NextResponse.json(
      { error: "Authorization flow expired. Please try again." },
      { status: 400 }
    );
  }

  try {
    const tokens = await exchangeCodeForTokens(code);

    // Pack tokens into an HMAC-signed query parameter instead of a URL fragment.
    // The client reads this once, stores in localStorage, and clears the URL.
    const tokenPayload = {
      access_token: tokens.access_token,
      refresh_token: tokens.refresh_token,
      expires_in: tokens.expires_in,
      scope: tokens.scope,
      connected: true,
      ts: Date.now(),
    };
    const tokenJson = JSON.stringify(tokenPayload);
    const tokenSig = crypto
      .createHmac("sha256", process.env.HMRC_CLIENT_SECRET || "")
      .update(tokenJson)
      .digest("hex");
    const dataParam = Buffer.from(
      JSON.stringify({ ...tokenPayload, sig: tokenSig })
    ).toString("base64url");

    const dashboardUrl = new URL("/dashboard/hmrc-connect", request.url);
    dashboardUrl.searchParams.set("data", dataParam);

    return NextResponse.redirect(dashboardUrl);
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Token exchange failed.";
    const dashboardUrl = new URL("/dashboard/hmrc-connect", request.url);
    dashboardUrl.searchParams.set("error", message);
    return NextResponse.redirect(dashboardUrl);
  }
}
