import Link from "next/link";
import Image from "next/image";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="bg-white/80 backdrop-blur-lg border-b border-gray-100 sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <Image src="/logo.svg" alt="QuarterlyUK" width={28} height={28} />
            <span className="text-lg font-bold tracking-tight text-primary">
              Quarterly<span className="text-accent">UK</span>
            </span>
          </Link>
          <Link
            href="/"
            className="text-sm font-medium text-muted hover:text-primary transition-colors"
          >
            Back to home
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-primary mb-2">Terms &amp; Conditions</h1>
        <p className="text-sm text-muted mb-10">Last updated: 18 February 2026</p>

        <div className="prose prose-sm max-w-none text-gray-700 space-y-6">
          <section>
            <h2 className="text-lg font-bold text-primary">1. About QuarterlyUK</h2>
            <p>
              QuarterlyUK (&ldquo;the Service&rdquo;, &ldquo;the Product&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is a browser-based
              record-keeping tool designed to help UK sole traders and landlords organise their
              income and expenses. It is provided by QuarterlyUK.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">2. Not Financial or Tax Advice</h2>
            <p>
              <strong>QuarterlyUK is a record-keeping tool, not a tax adviser, accountant, or
              financial adviser.</strong> The Service does not provide tax advice, financial advice,
              or legal advice of any kind. Any tax estimates, calculations, or summaries generated
              by the Service are for informational purposes only and should not be relied upon as
              accurate or complete.
            </p>
            <p>
              You are solely responsible for the accuracy of the data you enter and for verifying
              all calculations, summaries, and exports before submitting anything to HMRC or any
              other party. We strongly recommend that you consult a qualified accountant or tax
              professional before making any tax-related decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">3. No Liability for Calculations</h2>
            <p>
              To the fullest extent permitted by law, QuarterlyUK accepts no liability whatsoever
              for any loss, damage, penalty, fine, or additional tax liability arising from:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Errors or inaccuracies in any calculation, tax estimate, quarterly summary, or report generated by the Service</li>
              <li>Incorrect categorisation of income or expenses</li>
              <li>Reliance on any output of the Service without independent verification</li>
              <li>Late or incorrect submissions to HMRC based on data from the Service</li>
              <li>Any discrepancy between the Service&apos;s output and HMRC requirements</li>
            </ul>
            <p>
              <strong>You use the Service entirely at your own risk.</strong> The Service is provided
              &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
              whether express or implied, including but not limited to implied warranties of
              merchantability, fitness for a particular purpose, and non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">4. Local Data Storage &amp; Data Loss</h2>
            <p>
              All data you enter into QuarterlyUK is stored locally in your web browser
              using localStorage. <strong>We do not store, transmit, or have access to your data.</strong> This means:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Your data exists only on the device and browser where you entered it</li>
              <li>Clearing your browser data, cache, or cookies may permanently delete your records</li>
              <li>Switching browsers, devices, or using private/incognito mode means your data will not be available</li>
              <li>Browser updates or changes may affect stored data</li>
            </ul>
            <p>
              <strong>QuarterlyUK accepts no liability for any loss of data, howsoever caused.</strong> You
              are solely responsible for backing up your data regularly using the export and
              backup features provided. We strongly recommend downloading a backup after every
              session.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">5. HMRC Compliance</h2>
            <p>
              QuarterlyUK is designed to help you organise your records in preparation for
              Making Tax Digital (MTD) for Income Tax. However, <strong>QuarterlyUK is not
              HMRC-recognised bridging software and cannot submit data directly to HMRC.</strong>
            </p>
            <p>
              We make no guarantee that the Service meets all HMRC requirements for
              digital record-keeping under MTD. It is your responsibility to ensure that
              your record-keeping arrangements comply with all applicable HMRC regulations.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">6. Subscription &amp; Access</h2>
            <p>
              When you subscribe to QuarterlyUK, you receive a personal, non-transferable,
              non-exclusive license to use the full features of the Service for the duration
              of your active subscription. This includes:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Unlimited expense and income tracking</li>
              <li>Unlimited invoice creation</li>
              <li>CSV export and quarterly summaries</li>
              <li>All updates released during your subscription period</li>
            </ul>
            <p>
              Subscriptions are billed monthly via our payment processor, LemonSqueezy.
              Early subscribers (the first 1,000) receive a rate of £2.50 per month, locked
              in for 12 months from the date of subscription. We will give at least 30 days&apos;
              notice before any price change takes effect.
            </p>
            <p>
              The free tier is limited in functionality and is provided to allow you to evaluate
              the Service before subscribing.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">7. Cancellation &amp; Refunds</h2>
            <p>
              You may cancel your subscription at any time. Cancellation takes effect at the
              end of your current billing period. There are no cancellation fees or penalties.
              Since your data is stored locally in your browser, you retain access to all your
              records after cancelling. However, access to premium features (unlimited tracking,
              CSV exports) will revert to free tier limits.
            </p>
            <p>
              Refunds for the current billing period are handled on a case-by-case basis.
              If you experience a genuine technical issue that prevents you from using the
              Service, please contact us at{" "}
              <a href="mailto:hello@quarterlyuk.com" className="text-accent underline">
                hello@quarterlyuk.com
              </a>{" "}
              and we will do our best to resolve it or offer a refund where appropriate.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, in no event shall QuarterlyUK,
              its owners, employees, or affiliates be liable for any indirect, incidental, special,
              consequential, or punitive damages, including without limitation, loss of profits,
              data, use, goodwill, or other intangible losses, resulting from:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Your access to or use of (or inability to access or use) the Service</li>
              <li>Any conduct or content of any third party on the Service</li>
              <li>Any content obtained from the Service</li>
              <li>Unauthorised access, use, or alteration of your data</li>
            </ul>
            <p>
              Our total aggregate liability to you for any claims arising out of or relating to
              the use of the Service shall not exceed the amount you paid to us in the twelve (12)
              months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">9. Changes to These Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Changes will be posted on
              this page with an updated &ldquo;Last updated&rdquo; date. Your continued use of
              the Service after any changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">10. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with the laws of
              England and Wales. Any disputes arising under or in connection with these terms
              shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-primary">11. Contact</h2>
            <p>
              If you have any questions about these terms, please contact us at{" "}
              <a href="mailto:hello@quarterlyuk.com" className="text-accent underline">
                hello@quarterlyuk.com
              </a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="bg-primary-dark text-slate-400 py-8">
        <div className="max-w-4xl mx-auto px-6 text-center text-sm">
          <span>&copy; 2026 QuarterlyUK. All rights reserved.</span>
        </div>
      </footer>
    </div>
  );
}
